### PR TITLE
feat: add man pages and shell completions

### PR DESCRIPTION
**Pull request by donovanglover**
Auto-generated with clap.

### CODE REVIEW

**Comment by donovanglover** [comment]
Added missing `pub` to `jack` so `cargo clippy --all --all-features` should pass now

**Comment by chenrui333** [comment]
@chaosprint 👋 any chance that you can cut a new release for this change? Thanks!

**Comment by chaosprint** [comment]
> @chaosprint 👋 any chance that you can cut a new release for this change? Thanks!

done. https://github.com/chaosprint/asak/releases/tag/v0.3.4

**Comment by chenrui333** [comment]
Thanks @chaosprint!

**Pull request merged**
